### test
GET http://localhost:3000/ HTTP/1.1

### test api
GET http://localhost:3000/api/students?name=tay HTTP/1.1

### add student in db
POST http://localhost:3000/api/students/add HTTP/1.1
Content-Type: application/json

{
    "name":"sabir",
    "department":"DCS",
    "program":"BSCS",
    "semester":6
}


### get all students
GET http://localhost:3000/api/students HTTP/1.1

### get student by id
GET http://localhost:3000/api/students?id=649c8288a4ad1190ec602efe HTTP/1.1

### delete student
DELETE http://localhost:3000/api/students/delete?id=649c85b336f08da139291907 HTTP/1.1